- name: Check status of vault for seal
  shell: vault status -format=yaml
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  register: vault_status_raw
  failed_when:
    - vault_status_raw.rc == 1
  tags: unseal

- name: save vault_status
  set_fact:
    vault_status: "{{ vault_status_raw.stdout | from_yaml }}"
  tags: unseal

- name: Get unseal key files
  find:
    paths: "{{ unseal_keys_dir_output }}"
  register: found_key_files
  tags: unseal
  when: vault_status.sealed | bool

- name: Reading unseal key contents
  command: cat {{ item.path }}
  register: unseal_keys
  with_items: "{{ found_key_files.files }}"
  tags: unseal
  when: vault_status.sealed | bool

- name: Unseal vault with unseal keys
  shell: |
    vault operator unseal {{ item.stdout }}
  with_items: "{{unseal_keys.results}}"
  tags: unseal
  when: vault_status.sealed | bool
