- name: Get unseal key files
  find:
    paths: "{{ unseal_keys_dir_output }}"
  register: found_key_files
  tags: unseal

- name: Reading unseal key contents
  command: cat {{ item.path }}
  register: unseal_keys
  with_items: "{{ found_key_files.files }}"
  tags: unseal

- name: Unseal vault with unseal keys
  shell: |
    vault operator unseal {{ item.stdout }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  with_items: "{{unseal_keys.results}}"
  tags: unseal
