---
- name: Set domain to {{ domain_name }}
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#Domains="
    line: "Domains={{ domain_name }}"
  notify: "restart systemd-resolved"
  tags: domain
