- name: Create service override directory
  file:
    path: /etc/systemd/system/bootcamp-webservice.d
    state: directory
    recurse: yes

- name: Create service file
  template:
    src: bootcamp-webservice.service.j2
    dest: /etc/systemd/system/bootcamp-webservice.service

- name: Create override file
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/bootcamp-webservice.d/override.conf

- name: Enable bootcamp-webservice
  systemd:
    name: bootcamp-webservice
    masked: no
    enabled: yes
    state: started
