---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - vault

- hosts: all
  vars:
    unseal_keys_dir_output: "/var/opt/vault/unsealKey"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  roles:
    - vault-init
    - vault-unseal
    - vault-configure

- hosts: all
  roles:
    - samba
    - samba-configure
    - webservice

