---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - domain

- hosts: samba
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - vault

- hosts: samba
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  roles:
    - vault-init
    - vault-unseal
    - vault-configure

- hosts: samba
  roles:
    - samba
    - samba-configure
    - webservice

