---
# Copy LDIF directory to target

- name: Copy ldifs directory to remote
  copy:
    src: "{{ playbook_dir }}/ldifs"
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu

# ls -d returns the directory, with * the full path
- name: List files in remote directory
  shell: ls -d /home/ubuntu/ldifs/*
  register: ldif_files

- name: Add LDIFS
  shell: ldapadd -H ldaps://samba.bootcamp-partners.confluent.io -D Administrator@BOOTCAMP-PARTNERS.CONFLUENT.IO  -w Bootcamp4Ever -f "{{ item }}"
  register: ldapadd_result
  changed_when: ldapadd_result.rc == 0
  failed_when: ldapadd_result.rc != 0 and ldapadd_result.rc != 68
  with_items: "{{ ldif_files.stdout_lines }}"

- name: Copy scripts directory to remote
  copy:
    src: "{{ playbook_dir }}/scripts"
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu

